# ----
# Site

title: Trad Market 
url: "https://trad-market.github.io/"

snipcart_currency: "DZD"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Trad Market 
author:
  name: Trad Market 
  email: Trad-market@gmail.com
  twitter: Tradmark # twitter username without the @ symbol
  phone: "0542043860"
social:
  name: Trad Market
  links:
    - https://www.facebook.com/TradMark23?mibextid=ZbWKwL

# ------
# Build
timezone: Etc/UTC

collections:
  staff_members:
    output: false
  products:
    output: true

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

social_icons:
  - Email
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
